# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: catalog.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'catalog.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\x12\x12\x63loudscale.catalog\"\'\n\x11GetProductRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"\x80\x01\n\x12GetProductResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0b\n\x03sku\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x13\n\x0bprice_cents\x18\x05 \x01(\x03\x12\x11\n\tis_active\x18\x06 \x01(\x08\"C\n\x0ePriceCheckItem\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x1d\n\x15submitted_price_cents\x18\x02 \x01(\x03\"J\n\x15ValidatePricesRequest\x12\x31\n\x05items\x18\x01 \x03(\x0b\x32\".cloudscale.catalog.PriceCheckItem\"V\n\x15PriceValidationResult\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\r\n\x05valid\x18\x02 \x01(\x08\x12\x1a\n\x12\x61\x63tual_price_cents\x18\x03 \x01(\x03\"g\n\x16ValidatePricesResponse\x12\x11\n\tall_valid\x18\x01 \x01(\x08\x12:\n\x07results\x18\x02 \x03(\x0b\x32).cloudscale.catalog.PriceValidationResult2\xd6\x01\n\x0e\x43\x61talogService\x12[\n\nGetProduct\x12%.cloudscale.catalog.GetProductRequest\x1a&.cloudscale.catalog.GetProductResponse\x12g\n\x0eValidatePrices\x12).cloudscale.catalog.ValidatePricesRequest\x1a*.cloudscale.catalog.ValidatePricesResponseB\x18\n\x16\x63om.cloudscale.catalogb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.cloudscale.catalog'
  _globals['_GETPRODUCTREQUEST']._serialized_start=37
  _globals['_GETPRODUCTREQUEST']._serialized_end=76
  _globals['_GETPRODUCTRESPONSE']._serialized_start=79
  _globals['_GETPRODUCTRESPONSE']._serialized_end=207
  _globals['_PRICECHECKITEM']._serialized_start=209
  _globals['_PRICECHECKITEM']._serialized_end=276
  _globals['_VALIDATEPRICESREQUEST']._serialized_start=278
  _globals['_VALIDATEPRICESREQUEST']._serialized_end=352
  _globals['_PRICEVALIDATIONRESULT']._serialized_start=354
  _globals['_PRICEVALIDATIONRESULT']._serialized_end=440
  _globals['_VALIDATEPRICESRESPONSE']._serialized_start=442
  _globals['_VALIDATEPRICESRESPONSE']._serialized_end=545
  _globals['_CATALOGSERVICE']._serialized_start=548
  _globals['_CATALOGSERVICE']._serialized_end=762
# @@protoc_insertion_point(module_scope)
