# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\x14\x63loudscale.inventory\"*\n\x14GetStockLevelRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\"n\n\x15GetStockLevelResponse\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x17\n\x0f\x61vailable_stock\x18\x02 \x01(\x05\x12\x16\n\x0ereserved_stock\x18\x03 \x01(\x05\x12\x10\n\x08in_stock\x18\x04 \x01(\x08\"1\n\x1aGetBatchStockLevelsRequest\x12\x13\n\x0bproduct_ids\x18\x01 \x03(\t\"Z\n\x1bGetBatchStockLevelsResponse\x12;\n\x06levels\x18\x01 \x03(\x0b\x32+.cloudscale.inventory.GetStockLevelResponse2\xf8\x01\n\x10InventoryService\x12h\n\rGetStockLevel\x12*.cloudscale.inventory.GetStockLevelRequest\x1a+.cloudscale.inventory.GetStockLevelResponse\x12z\n\x13GetBatchStockLevels\x12\x30.cloudscale.inventory.GetBatchStockLevelsRequest\x1a\x31.cloudscale.inventory.GetBatchStockLevelsResponseB\x1a\n\x18\x63om.cloudscale.inventoryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\030com.cloudscale.inventory'
  _globals['_GETSTOCKLEVELREQUEST']._serialized_start=41
  _globals['_GETSTOCKLEVELREQUEST']._serialized_end=83
  _globals['_GETSTOCKLEVELRESPONSE']._serialized_start=85
  _globals['_GETSTOCKLEVELRESPONSE']._serialized_end=195
  _globals['_GETBATCHSTOCKLEVELSREQUEST']._serialized_start=197
  _globals['_GETBATCHSTOCKLEVELSREQUEST']._serialized_end=246
  _globals['_GETBATCHSTOCKLEVELSRESPONSE']._serialized_start=248
  _globals['_GETBATCHSTOCKLEVELSRESPONSE']._serialized_end=338
  _globals['_INVENTORYSERVICE']._serialized_start=341
  _globals['_INVENTORYSERVICE']._serialized_end=589
# @@protoc_insertion_point(module_scope)
