# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inventory_pb2 as inventory__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inventory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventoryServiceStub:
    """Service for querying real-time stock availability.
    Used synchronously by the API Gateway or Order Service to display
    stock status before initiating the asynchronous checkout Saga.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStockLevel = channel.unary_unary(
                '/cloudscale.inventory.InventoryService/GetStockLevel',
                request_serializer=inventory__pb2.GetStockLevelRequest.SerializeToString,
                response_deserializer=inventory__pb2.GetStockLevelResponse.FromString,
                _registered_method=True)
        self.GetBatchStockLevels = channel.unary_unary(
                '/cloudscale.inventory.InventoryService/GetBatchStockLevels',
                request_serializer=inventory__pb2.GetBatchStockLevelsRequest.SerializeToString,
                response_deserializer=inventory__pb2.GetBatchStockLevelsResponse.FromString,
                _registered_method=True)


class InventoryServiceServicer:
    """Service for querying real-time stock availability.
    Used synchronously by the API Gateway or Order Service to display
    stock status before initiating the asynchronous checkout Saga.
    """

    def GetStockLevel(self, request, context):
        """Returns the current stock level for a single product.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBatchStockLevels(self, request, context):
        """Batch query for stock levels across multiple products.
        Used by the catalog listing page to display availability badges.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStockLevel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStockLevel,
                    request_deserializer=inventory__pb2.GetStockLevelRequest.FromString,
                    response_serializer=inventory__pb2.GetStockLevelResponse.SerializeToString,
            ),
            'GetBatchStockLevels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBatchStockLevels,
                    request_deserializer=inventory__pb2.GetBatchStockLevelsRequest.FromString,
                    response_serializer=inventory__pb2.GetBatchStockLevelsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloudscale.inventory.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloudscale.inventory.InventoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventoryService:
    """Service for querying real-time stock availability.
    Used synchronously by the API Gateway or Order Service to display
    stock status before initiating the asynchronous checkout Saga.
    """

    @staticmethod
    def GetStockLevel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudscale.inventory.InventoryService/GetStockLevel',
            inventory__pb2.GetStockLevelRequest.SerializeToString,
            inventory__pb2.GetStockLevelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBatchStockLevels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudscale.inventory.InventoryService/GetBatchStockLevels',
            inventory__pb2.GetBatchStockLevelsRequest.SerializeToString,
            inventory__pb2.GetBatchStockLevelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
