"""initial_schema

Revision ID: 02196549ae29
Revises: 
Create Date: 2026-07-11 14:43:29.551820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02196549ae29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_tenant_id'), 'products', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # Enable Row-Level Security (PostgreSQL only)
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        from cloudscale_shared.v2_postgresql_rls_migration import generate_rls_migration, generate_tenant_context_function
        # Create set_tenant_context function if not exists
        op.execute(generate_tenant_context_function())
        op.execute(generate_rls_migration("products", "tenant_id"))


def downgrade() -> None:
    """Downgrade schema."""
    # Enable Row-Level Security rollback (PostgreSQL only)
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        from cloudscale_shared.v2_postgresql_rls_migration import generate_rollback_migration
        op.execute(generate_rollback_migration("products"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_tenant_id'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
