from cloudscale_shared.database import (
    DatabaseSessionManager,
    RedisManager,
    cursor_paginate,
    get_db_session,
    get_read_db_session,
    get_redis_client,
    init_db,
    init_redis,
)
from cloudscale_shared.events import Event, KafkaConsumerWrapper, KafkaProducerWrapper
from cloudscale_shared.exceptions import (
    CloudScaleException,
    ConflictException,
    ForbiddenException,
    NotFoundException,
    UnauthorizedException,
    ValidationException,
    setup_exception_handlers,
)
from cloudscale_shared.inbox import InboxMixin, inbox_already_processed, record_inbox
from cloudscale_shared.logging import setup_logging
from cloudscale_shared.metrics import register_health_routes, setup_metrics
from cloudscale_shared.middleware import CorrelationIdMiddleware, TenantContextMiddleware, get_current_tenant
from cloudscale_shared.outbox import OutboxMixin, OutboxWorker, write_outbox
from cloudscale_shared.query import Page, PageParams
from cloudscale_shared.repository import AbstractRepository, SQLAlchemyRepository
from cloudscale_shared.security import (
    RateLimiter,
    RoleChecker,
    SecurityHeadersMiddleware,
    audit_log,
    clear_failed_logins,
    create_token_pair,
    decode_token,
    hash_password,
    is_account_locked,
    is_token_revoked,
    password_needs_rehash,
    record_failed_login,
    revoke_token,
    validate_password_policy,
    verify_password,
)
from cloudscale_shared.tracing import extract_trace_from_event, get_current_ids, inject_trace_into_event, setup_tracing
from cloudscale_shared.uow import AbstractUnitOfWork, SQLAlchemyUnitOfWork

__all__ = [
    "setup_logging",
    "CorrelationIdMiddleware",
    "TenantContextMiddleware",
    "get_current_tenant",
    "init_db",
    "init_redis",
    "get_db_session",
    "get_read_db_session",
    "get_redis_client",
    "DatabaseSessionManager",
    "RedisManager",
    "cursor_paginate",
    "Event",
    "KafkaProducerWrapper",
    "KafkaConsumerWrapper",
    "CloudScaleException",
    "NotFoundException",
    "ConflictException",
    "UnauthorizedException",
    "ForbiddenException",
    "ValidationException",
    "setup_exception_handlers",
    "AbstractRepository",
    "SQLAlchemyRepository",
    "AbstractUnitOfWork",
    "SQLAlchemyUnitOfWork",
    "PageParams",
    "Page",
    "setup_metrics",
    "OutboxMixin",
    "write_outbox",
    "OutboxWorker",
    "InboxMixin",
    "inbox_already_processed",
    "record_inbox",
    "hash_password",
    "verify_password",
    "password_needs_rehash",
    "validate_password_policy",
    "create_token_pair",
    "decode_token",
    "revoke_token",
    "is_token_revoked",
    "record_failed_login",
    "is_account_locked",
    "clear_failed_logins",
    "RoleChecker",
    "RateLimiter",
    "SecurityHeadersMiddleware",
    "audit_log",
    "retry_with_backoff",
    "circuit_breaker",
    "CircuitBreaker",
    "CircuitState",
    "CircuitBreakerOpenException",
    "bulkhead",
    "Bulkhead",
    "BulkheadLimitExceeded",
    "with_timeout",
    "cache_aside",
    "invalidate_cache_key",
]

from cloudscale_shared.cache import (
    cache_aside,
    invalidate_cache_key,
)
from cloudscale_shared.resilience import (
    Bulkhead,
    BulkheadLimitExceeded,
    CircuitBreaker,
    CircuitBreakerOpenException,
    CircuitState,
    bulkhead,
    circuit_breaker,
    retry_with_backoff,
    with_timeout,
)
