apiVersion: v2
name: cloudscale-parent
description: CloudScale Commerce — Production-Grade E-Commerce Platform
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: auth-service
    version: 1.0.0
    condition: auth-service.enabled
  - name: catalog-service
    version: 1.0.0
    condition: catalog-service.enabled
  - name: inventory-service
    version: 1.0.0
    condition: inventory-service.enabled
  - name: order-service
    version: 1.0.0
    condition: order-service.enabled
  - name: payment-service
    version: 1.0.0
    condition: payment-service.enabled
  - name: notification-service
    version: 1.0.0
    condition: notification-service.enabled
