# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x0f\x63loudscale.auth\",\n\x14ValidateTokenRequest\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\"T\n\x15ValidateTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04role\x18\x04 \x01(\t\"%\n\x12GetUserInfoRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"j\n\x13GetUserInfoResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x11\n\tlast_name\x18\x04 \x01(\t\x12\x0c\n\x04role\x18\x05 \x01(\t2\xc7\x01\n\x0b\x41uthService\x12^\n\rValidateToken\x12%.cloudscale.auth.ValidateTokenRequest\x1a&.cloudscale.auth.ValidateTokenResponse\x12X\n\x0bGetUserInfo\x12#.cloudscale.auth.GetUserInfoRequest\x1a$.cloudscale.auth.GetUserInfoResponseB\x15\n\x13\x63om.cloudscale.authb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\023com.cloudscale.auth'
  _globals['_VALIDATETOKENREQUEST']._serialized_start=31
  _globals['_VALIDATETOKENREQUEST']._serialized_end=75
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=77
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=161
  _globals['_GETUSERINFOREQUEST']._serialized_start=163
  _globals['_GETUSERINFOREQUEST']._serialized_end=200
  _globals['_GETUSERINFORESPONSE']._serialized_start=202
  _globals['_GETUSERINFORESPONSE']._serialized_end=308
  _globals['_AUTHSERVICE']._serialized_start=311
  _globals['_AUTHSERVICE']._serialized_end=510
# @@protoc_insertion_point(module_scope)
