# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import catalog_pb2 as catalog__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in catalog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CatalogServiceStub:
    """Service for retrieving product details and validating prices.
    Used by Order Service during checkout to verify that the product
    exists and the submitted price matches the current catalog price.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProduct = channel.unary_unary(
                '/cloudscale.catalog.CatalogService/GetProduct',
                request_serializer=catalog__pb2.GetProductRequest.SerializeToString,
                response_deserializer=catalog__pb2.GetProductResponse.FromString,
                _registered_method=True)
        self.ValidatePrices = channel.unary_unary(
                '/cloudscale.catalog.CatalogService/ValidatePrices',
                request_serializer=catalog__pb2.ValidatePricesRequest.SerializeToString,
                response_deserializer=catalog__pb2.ValidatePricesResponse.FromString,
                _registered_method=True)


class CatalogServiceServicer:
    """Service for retrieving product details and validating prices.
    Used by Order Service during checkout to verify that the product
    exists and the submitted price matches the current catalog price.
    """

    def GetProduct(self, request, context):
        """Retrieves product details by ID. Returns NOT_FOUND if the product
        does not exist or is inactive.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidatePrices(self, request, context):
        """Validates that the submitted prices match the catalog. Used during
        order creation to prevent price manipulation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=catalog__pb2.GetProductRequest.FromString,
                    response_serializer=catalog__pb2.GetProductResponse.SerializeToString,
            ),
            'ValidatePrices': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidatePrices,
                    request_deserializer=catalog__pb2.ValidatePricesRequest.FromString,
                    response_serializer=catalog__pb2.ValidatePricesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloudscale.catalog.CatalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloudscale.catalog.CatalogService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CatalogService:
    """Service for retrieving product details and validating prices.
    Used by Order Service during checkout to verify that the product
    exists and the submitted price matches the current catalog price.
    """

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudscale.catalog.CatalogService/GetProduct',
            catalog__pb2.GetProductRequest.SerializeToString,
            catalog__pb2.GetProductResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidatePrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloudscale.catalog.CatalogService/ValidatePrices',
            catalog__pb2.ValidatePricesRequest.SerializeToString,
            catalog__pb2.ValidatePricesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
