apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cloudscale.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cloudscale.labels" . | nindent 4 }}
  annotations:
    konghq.com/strip-path: "false"
    konghq.com/protocols: "https"
    konghq.com/plugins: rate-limiting-inventory,cors-inventory
    kubernetes.io/ingress.class: kong
spec:
  tls:
    - hosts:
        - api.cloudscale.io
      secretName: cloudscale-tls
  rules:
    - host: api.cloudscale.io
      http:
        paths:
          - path: /api/v1/inventory
            pathType: Prefix
            backend:
              service:
                name: {{ include "cloudscale.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
