apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudscale.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cloudscale.labels" . | nindent 4 }}
data:
  SERVICE_NAME: {{ .Chart.Name }}
  DATABASE_URL: "postgresql+asyncpg://{{ .Values.global.postgres.user }}:{{ .Values.global.postgres.password }}@{{ .Values.global.postgres.host }}:{{ .Values.global.postgres.port }}/{{ .Values.database.name }}"
  REDIS_URL: "redis://{{ .Values.global.redis.host }}:{{ .Values.global.redis.port }}/{{ .Values.database.redisDb }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.global.otel.endpoint | quote }}
