global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alert.rules"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "auth-service"
    static_configs:
      - targets: ["auth-service:8000"]

  - job_name: "catalog-service"
    static_configs:
      - targets: ["catalog-service:8000"]

  - job_name: "inventory-service"
    static_configs:
      - targets: ["inventory-service:8000"]

  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:8000"]

  - job_name: "payment-service"
    static_configs:
      - targets: ["payment-service:8000"]

  - job_name: "notification-service"
    static_configs:
      - targets: ["notification-service:8000"]
