apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudscale.fullname" . }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cloudscale.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET_KEY: {{ .Values.global.jwt.secretKey | b64enc | quote }}
